.PHONY: clean All

All:
	@echo "----------Building project:[ koreanDrama - Debug ]----------"
	@cd "koreanDrama" && "$(MAKE)" -f  "koreanDrama.mk"
clean:
	@echo "----------Cleaning project:[ koreanDrama - Debug ]----------"
	@cd "koreanDrama" && "$(MAKE)" -f  "koreanDrama.mk" clean
