.PHONY: clean All

All:
	@echo "----------Building project:[ VerticalJump - Debug ]----------"
	@cd "VerticalJump" && "$(MAKE)" -f  "VerticalJump.mk"
clean:
	@echo "----------Cleaning project:[ VerticalJump - Debug ]----------"
	@cd "VerticalJump" && "$(MAKE)" -f  "VerticalJump.mk" clean
